
on:
  push:
    branches:
      - main
      - staging

env:
  AZURE_WEBAPP_NAME: nh4hmatchmaker
  AZURE_WEBAPP_PACKAGE_PATH: './build/'
  NODE_VERSION: '16.x'
  DEPLOYMENT_SLOT_PRODUCTION: 'production'
  CI: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test --if-present
      run: |
        npm install
        npm run build --if-present

    - name: 'Deploy to Azure WebApp Production'
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: ${{ env.DEPLOYMENT_SLOT_PRODUCTION }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE_NH4H_USERREG_PROD }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
